version: '3.8'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGO_URL=mongodb://mongodb:27017/customerData
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
    volumes:
      - .:/src
    networks:
      - node-network

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge